name: Deploy WordPress

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up EC2 instance
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 php libapache2-mod-php php-mysql

      - name: Set up MySQL database
        run: |
          sudo mysql_secure_installation
          sudo mysql -e "CREATE DATABASE wordpress;"
          sudo mysql -e "GRANT ALL ON wordpress.* TO 'wordpressuser'@'localhost' IDENTIFIED BY 'redhat';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Deploy WordPress
        run: |
          sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.EC2_INSTANCE_PASSWORD }} scp -o StrictHostKeyChecking=no -r ./ ubuntu@43.204.130.21:/var/www/html/

      - name: Configure WordPress
        run: |
          sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.EC2_INSTANCE_PASSWORD }} ssh -o StrictHostKeyChecking=no ubuntu@43.204.130.21 "sudo mysql -e 'CREATE DATABASE wordpress;' && sudo mysql -e 'GRANT ALL ON wordpress.* TO 'wordpressuser'@'localhost' IDENTIFIED BY 'password';' && sudo mysql -e 'FLUSH PRIVILEGES;'"

      - name: Restart Apache
        run: |
          sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.EC2_INSTANCE_PASSWORD }} ssh -o StrictHostKeyChecking=no ubuntu@43.204.130.21 "sudo systemctl restart apache2"
